version: '2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  postgres:    
    container_name: postgres-booking-characteres
    image: postgres:10.6
    ports:
      - "5432:5432"
    environment:            
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=booking_characteres
      - TZ=UTC
    volumes:
      - ./resources/create-database.sh:/docker-entrypoint-initdb.d/create-database.sh
#    networks:
#       - app-private-network

#networks:
#  app-private-network:
#    driver: bridge
#    name: app-private-network