FROM postgres:10.6

ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=booking-characteres

COPY create-postgresql-database.sh:/docker-entrypoint-initdb.d/create-postgresql-database.sh

EXPOSE 5432
